version: '3.3'
services:

  server:
    image: timveil/oo-docker-onprem-server:latest
    environment:
      - SERVER_HOSTNAME=localhost
      - STORAGE_HOSTNAME=server
    ports:
      - "8080:8080"

  collector:
    image: timveil/oo-docker-onprem-collector:rootless
    env_file:
      - overops-key.env
    environment:
      - SERVICE_PRECONDITION=server:8080
      - TAKIPI_BACKEND_URL=http://server:8080
    ports:
      - "6060:6060"

  webhook:
    image: timveil/oo-webhook-example:alpine
    ports:
      - "8090:8090"

  agent:
    image: timveil/oo-docker-agent:rootless
    environment:
      - SERVICE_PRECONDITION=server:8080