version: '3.3'
services:
  storage:
    image: timveil/oo-docker-hybrid-storage:latest
    volumes:
      - ${VOLUME_SOURCE}:/opt/takipi-storage/storage
    ports:
      - "8080:8080"
      - "8081:8081"
  collector:
    image: timveil/oo-docker-remote-collector:latest
    environment:
      - TAKIPI_SECRET_KEY=${SECRET_KEY}
    ports:
      - "6060:6060"
  java-agent:
    image: timveil/oo-docker-agent:latest
    environment:
      - TAKIPI_SECRET_KEY=${SECRET_KEY}
      - TAKIPI_MASTER_HOST=collector
    depends_on:
      - collector