version: '3'
services:
  storage:
    build:
      context: ./storage
    ports:
      - "8080:8080"
      - "8081:8081"
  collector:
    build:
      context: ./collector
      args:
          - A_SECRET_KEY=${SECRET_KEY}
    ports:
      - "6060:6060"
  java-agent:
    build:
      context: ./agent-java
      args:
          - A_SECRET_KEY=${SECRET_KEY}
    depends_on:
      - collector