version: '3'
services:
  analysis-server:
    build:
      context: ./analysis-server
    ports:
      - "8080:8080"
  collector:
    build:
      context: ./collector
    depends_on:
      - analysis-server