version: '3'
services:
  analysis-server:
    build:
      context: ./analysis-server
    ports:
      - "8080:8080"
  collector:
    build:
      context: ./collector
      args:
          - A_SECRET_KEY=${SECRET_KEY}
          - A_COLLECTOR_PORT=${COLLECTOR_PORT}
    depends_on:
      - analysis-server
