version: '3'
services:
  analysis-server:
    build:
      context: ./analysis-server
    ports:
      - "8080:8080"
  collector:
    build:
      context: ./collector
      args:
        - SECRET_KEY=${SECRET_KEY}
        - COLLECTOR_PORT=${COLLECTOR_PORT}
    depends_on:
      - analysis-server
  java-agent:
    build:
      context: ./agent-java-jam
      args:
        - SECRET_KEY=${SECRET_KEY}
        - COLLECTOR_PORT=${COLLECTOR_PORT}
    depends_on:
      - collector