version: '3.3'
services:

  db:
    image: postgres:10
    command: postgres -N 500
    environment:
      POSTGRES_PASSWORD: overops

  web:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@takipi.com
      PGADMIN_DEFAULT_PASSWORD: overops
    ports:
      - "8082:80"

  server:
    image: timveil/oo-docker-onprem-server:postgres
    environment:
      - SERVICE_PRECONDITION=db:5432
      - SERVER_HOSTNAME=localhost
      - STORAGE_HOSTNAME=server
    ports:
      - "8080:8080"

  collector:
    image: timveil/oo-docker-onprem-collector:rootless
    env_file:
      - overops-key.env
    environment:
      - SERVICE_PRECONDITION=server:8080
      - TAKIPI_BACKEND_URL=http://server:8080
    ports:
      - "6060:6060"

  agent:
    image: timveil/oo-docker-agent:latest
    environment:
      - SERVICE_PRECONDITION=server:8080
    ports:
      - "8081:8080"