version: '3.3'
services:

  server:
    image: timveil/oo-docker-onprem-server:latest
    ports:
      - "8080:8080"

  # todo: implement precondition env variable
  collector:
    image: timveil/oo-docker-onprem-collector:latest
    env_file:
      - overops-key.env
    environment:
      - TAKIPI_BACKEND_URL=http://server:8080
    ports:
      - "6060:6060"

  # default agent properties are sufficient
  agent:
    image: timveil/oo-docker-agent:latest