version: '3'
services:
  collector:
    build:
      context: ./collector
      args:
          - A_SECRET_KEY=${SECRET_KEY}
    ports:
      - "6060:6060"
  agent-java:
    build:
      context: ./agent-java
      args:
          - A_SECRET_KEY=${SECRET_KEY}
    depends_on:
      - collector