version: '3.3'
services:

  db:
    image: mysql:5
    command: mysqld --max-connections=500
    environment:
      MYSQL_ROOT_PASSWORD: overops
      MYSQL_ROOT_HOST: "%"

  db-ui:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: overops
    links:
      - db
    ports:
    - "8082:80"

  server:
    image: timveil/oo-docker-onprem-server:mysql
    environment:
      - SERVICE_PRECONDITION=db:3306
      - HOST_URL=server
      - FRONTEND_URL=http://localhost:8080
    ports:
      - "8080:8080"

  collector:
    image: timveil/oo-docker-onprem-collector:rootless
    env_file:
      - overops-key.env
    environment:
      - SERVICE_PRECONDITION=server:8080
      - TAKIPI_BACKEND_URL=http://server:8080
    ports:
      - "6060:6060"

  agent:
    image: timveil/oo-docker-agent:latest
    environment:
      - SERVICE_PRECONDITION=server:8080
    ports:
      - "8081:8080"