version: '3.2'
services:

  collector:
    image: timveil/oo-docker-remote-collector:latest
    env_file:
      - overops-key.env
    ports:
      - "6060:6060"

  sidecar:
    image: timveil/oo-docker-agent-sidecar
    volumes:
      - sidecar-volume:/opt/takipi

  agent:
    image: timveil/overops-event-generator
    env_file:
      - overops-agent.env
    environment:
      - TAKIPI_ARGS=takipi.server.name=mounted-agent-container
    volumes:
      - sidecar-volume:/sidecar
    ports:
      - "8080:8080"

volumes:
  sidecar-volume: