version: '3.2'
services:
  collector:
    image: timveil/overops-remote-collector:latest
    environment:
       - TAKIPI_SECRET_KEY=${SECRET_KEY}
    ports:
      - "6060:6060"
  agent-java:
    build:
      context: ./agent-java
    volumes:
      - /Users/timveil/dev/takipi/t4c-agent:/opt/takipi
    environment:
      - TAKIPI_SECRET_KEY=${SECRET_KEY}
      - TAKIPI_MASTER_HOST=collector
      - TAKIPI_MASTER_PORT=6060
      - TAKIPI_MACHINE_NAME=java-agent
      - TAKIPI_ARGS="takipi.debug.logconsole"
      - LD_LIBRARY_PATH=/opt/takipi/lib
      - JAVA_TOOL_OPTIONS=-agentlib:TakipiAgent
    depends_on:
      - collector