version: '3.2'
services:
  collector:
    build:
      context: ./collector
      args:
          - A_SECRET_KEY=${SECRET_KEY}
    ports:
      - "6060:6060"
  agent-java:
    volumes:
      - /Users/timveil/dev/takipi/t4c-agent:/opt/takipi
    environment:
      - LD_LIBRARY_PATH=/opt/takipi/lib
      - JAVA_TOOL_OPTIONS=-agentlib:TakipiAgent
      - TAKIPI_SECRET_KEY=${SECRET_KEY}
      - TAKIPI_MASTER_HOST=collector
      - TAKIPI_MASTER_PORT=6060
      - TAKIPI_ARGS="takipi.debug.logconsole,takipi.name=java-agent,takipi.deployment.name=v1.3.1”
    build:
      context: ./agent-java
    depends_on:
      - collector