version: '3.2'
services:

  collector:
    image: timveil/oo-docker-remote-collector:latest
    env_file:
      - overops-key.env
    ports:
      - "6060:6060"

  sidecar:
    image: timveil/oo-docker-agent-sidecar
    volumes:
      - sidecar-volume:/opt/takipi

  agent:
    image: timveil/oo-docker-mounted-agent:latest
    env_file:
      - overops-agent.env
    environment:
      - TAKIPI_ARGS=takipi.debug.logconsole,takipi.machine.name=mounted-agent-container
    volumes:
      - sidecar-volume:/sidecar

volumes:
  sidecar-volume: