version: '3.3'
services:

  storage:
    image: timveil/oo-docker-hybrid-storage:latest
    volumes:
      - storage-volume:/opt/takipi-storage/storage
    ports:
      - "8080:8080"
      - "8081:8081"

  collector:
    image: timveil/oo-docker-remote-collector:rootless
    env_file:
      - overops-key.env
    environment:
      - SERVICE_PRECONDITION=storage:8080
    ports:
      - "6060:6060"

  agent:
    image: timveil/oo-docker-agent:latest
    environment:
      - SERVICE_PRECONDITION=collector:6060
    ports:
      - "8082:8080"

# using docker named volume mount to store hybrid data; could alternatively use a bind mound on docker host
volumes:
  storage-volume:
