version: '3.3'
services:

  collector:
    image: timveil/oo-docker-remote-collector:latest
    env_file:
      - overops-key.env
    ports:
      - "6060:6060"

  sidecar:
    image: timveil/oo-docker-agent-sidecar
    volumes:
      - sidecar_volume:/opt/takipi

  cassandra:
    image: cassandra:latest
    env_file:
      - overops-agent.env
    environment:
      - TAKIPI_ARGS=takipi.debug.logconsole,takipi.machine.name=cassandra-container
    volumes:
      - sidecar_volume:/sidecar

volumes:
  sidecar_volume: