version: '3.3'
services:
  collector:
    image: timveil/overops-remote-collector:latest
    environment:
          - TAKIPI_SECRET_KEY=${SECRET_KEY}
    ports:
      - "6060:6060"
  cassandra:
    image: cassandra:latest
    volumes:
      - /Users/timveil/dev/takipi/t4c-agent:/opt/takipi
    environment:
      - LD_LIBRARY_PATH=/opt/takipi/lib
      - JAVA_TOOL_OPTIONS=-agentlib:TakipiAgent
      - TAKIPI_SECRET_KEY=${SECRET_KEY}
      - TAKIPI_MASTER_HOST=collector
      - TAKIPI_MASTER_PORT=6060
      - TAKIPI_ARGS="takipi.debug.logconsole,takipi.name=cassandra,takipi.deployment.name=cassandra-latest"
    depends_on:
      - collector