apiVersion: v1
kind: Service

metadata:
  name: agent-service

spec:

  selector:
    app: overops
    component: agent

  ports:
    - protocol: TCP
      name: web-ui
      port: 8080
      targetPort: 8080