version: '3.3'
services:

  server:
    image: timveil/oo-docker-onprem-server:h2
    environment:
      - HOST_URL=server
      - FRONTEND_URL=http://localhost:8080
    ports:
      - "8080:8080"
      - "8082:8082"

  collector:
    image: timveil/oo-docker-remote-collector:rootless
    env_file:
      - overops-key.env
    environment:
      - SERVICE_PRECONDITION=server:8080
      - TAKIPI_BACKEND_URL=http://server:8080
    ports:
      - "6060:6060"

  agent:
    image: timveil/oo-docker-agent:latest
    environment:
      - SERVICE_PRECONDITION=server:8080
    ports:
      - "8081:8080"